#!/bin/sh

EMAIL=$1
USER=$(echo "$EMAIL" | cut -d '@' -f 1)
HOST=$(echo "$EMAIL" | cut -d '@' -f 2)
CA=ca.gautier.org
VAULT_PATH="$PKI_ROOT/$CA"

mkdir -p "$VAULT_PATH/clients"
easypki create --ca-name $CA --client --expire 3650 --email $EMAIL $EMAIL
if ! [ -f "$VAULT_PATH/public/clients@$HOST.pem" ] ; then
 cat "$VAULT_PATH/public/ca.gautier.org.pem" > "$VAULT_PATH/public/clients@$HOST.pem"
fi
mkdir -p $VAULT_PATH/tmp
cat "$VAULT_PATH/public/clients@$HOST.pem" > "$VAULT_PATH/tmp/clients@$HOST.tmp"
cat "$VAULT_PATH/certs/$EMAIL.crt" "$VAULT_PATH/tmp/clients@$HOST.tmp" > "$VAULT_PATH/public/clients@$HOST.pem"
rm -r "$VAULT_PATH/tmp"
chmod +r-w $VAULT_PATH/public/clients@$HOST.pem

openssl pkcs12 -export -inkey $VAULT_PATH/keys/$EMAIL.key -in $VAULT_PATH/certs/$EMAIL.crt -certfile $VAULT_PATH/public/ca.gautier.org.pem -out $VAULT_PATH/public/$EMAIL.pfx
chmod +r-w $VAULT_PATH/public/$EMAIL.pfx

/bin/vault-refresh ca
