#!/bin/sh
if [ -f $PKI_ROOT/root/.last ] ; then
 date +%s > "$PKI_ROOT/root/.last"
fi 
if [ -f $PKI_ROOT/ca.gautier.org/.last ] ; then
 date +%s > "$PKI_ROOT/ca.gautier.org/.last"
fi 

easypki crl --ca-name ca.gautier.org --expire 1 > $PKI_ROOT/ca.gautier.org/public/ca.gautier.org.crl
chmod +rw $PKI_ROOT/ca.gautier.org/public/ca.gautier.org.crl