#!/bin/sh

HOST=$1
VAULT=ca

if [ ! -f /opt/pki-data/$VAULT.vhd ] ; then
 echo "[ERROR] Virtual hard disk file does not exist"
fi

sudo cryptsetup status $VAULT.evhd
if [ $? -eq 0 ] ;  then # check device exists
    echo "[ERROR] Encrypted hard drive status is unknown"
fi

# Check that device is mounted
if [ ! -f /opt/pki-data/ca.vhd ] ; then
 
fi

easypki --root /mnt/$VAULT create --ca-name ca.gautier.local --expire 3650 --dns $HOST $HOST

mkdir -p /mnt/$VAULT/public
VAULT_PATH=/mnt/$VAULT/ca.gautier.local
cat $VAULT_PATH/certs/$HOST.crt $VAULT_PATH/certs/ca.gautier.local.crt > $VAULT_PATH/public/$HOST.pem
chmod +r-w $VAULT_PATH/public/$HOST.pem


