version: "3.9"
services:
  pki:
    dns:
      - 192.168.4.200
      - 192.168.4.201
      - 192.168.4.203
      - 192.168.4.204
    build:
      args:
        ALPINE_VERSION: "latest"
        CRYPTSETUP_VERSION: "2.6.0"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "pki:dev"
    image: "pki:dev"
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"

volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/pki/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/pki/backup-volume
      
