version: "3.9"
services:
  pki:
    dns:
      - 10.0.4.200
      - 10.0.4.201
    build:
      args:
        ALPINE_VERSION: "latest"
        CRYPTSETUP_VERSION: "2.5.0"
        CRYPTSETUP_RELEASE: "2"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "pki:dev"
    image: "pki:dev"
    hostname: "pki"
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"

volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/pki/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/pki/backup-volume
      
