#!/bin/ash

# domain-setup: Creates the intermediate certificate authority for a specific domain

MOUNT_POINT=/mnt/vault
DOMAIN=$1

# echo "[INFO] Unmount vault"
/bin/mountpoint -q $MOUNT_POINT
if [ $? -eq 0 ] ; then
 cd $MOUNT_POINT/ca
 /usr/bin/easypki --root $MOUNT_POINT/ca create --ca-name root --filename ca.$DOMAIN --intermediate "Certificate Authority for ca.$DOMAIN"
fi

