#!/usr/bin/python3

import sys

fqdn = sys.argv
tokens = fqdn[1].split(".")
if 3 != len(tokens):
 print("[ERROR] FQDN must be host.domain.tld format")
 sys.exit(1) 
if 0 < len(tokens[2]): 
 print("%s.%s" % (tokens[1], tokens[2]))
else:
 print("%s" % tokens[1])

