#!/usr/bin/env python3

import sys
import fqdn

if __name__ == "__main__":
    args = sys.argv
    assert 3==len(args), "[ERROR] Parameters missing 'fqdn-parser fqdn token'"
    tokens = fqdn.parse(args[1])
    match args[2]:
        case "host":
            print( "%(host)s" % tokens )
        case "domain":
            print( "%(domain)s" % tokens )
        case "tld": 
            print( "%(tld)s" % tokens )
        case "domain.tld": 
            print( "%(domain)s.%(tld)s" % tokens )
        case _: 
            print( "%(host)s.%(domain)s.%(tld)s" % tokens )


