#!/bin/sh

# Script to run once on the first run to setup ca-root and ca vaults which will:
# 1. create the vaults
# 2. create the keys in the ca-root vault
# 3. create the keys for ca
# 4. Link the ca-root and ca together

vault-umount ca-root
vault-umount ca

vault-setup ca-root
vault-setup ca

# vault-mount ca-root
# vault-mount ca

# Create root
DOMAIN=$1
easypki --root /mnt/ca-root create --filename root --ca "Personal Certificate Authority - $DOMAIN"

easypki --root /mnt/ca-root create --ca-name root --filename ca.$DOMAIN --intermediate "Certificate Authority for ca.$DOMAIN"

mv /mnt/ca-root/ca.$DOMAIN /mnt/ca/ca.$DOMAIN

# mkdir -p /mnt/ca/public
# cat /mnt/ca/ca.gautier.local/certs/ca.gautier.local.crt > /mnt/ca/public/ca.gautier.local.pem
# easypki --root /mnt/ca create --ca-name ca.gautier.local --expire 3650 --dns test.gautier.local test.gautier.local

