#!/bin/ash

# Script to run once on the first run to setup ca-root and ca vaults which will:
# 1. create the vaults
# 2. create the keys for ca-root vault
# 3. create the keys for ca
# 4. Link the ca-root and ca together
# finally unmount vault ca-root
# refresh vault ca
if [ -z $1 ] ; then
 echo "[ERROR] Domain default is required for initial pki setup"
 exit 99
fi

if [ -f /opt/pki/$1.vhd ] ; then
 echo "[ERROR] CA vault is already created"
 exit 97
fi

vault-umount $1
vault-setup $1
date +%s > /mnt/$1/.last


# # Build CA
# easypki --root /mnt/$1 create --filename root --ca "Personal Certificate Authority - $1"
# # Build CA (Intermediate)
# easypki --root /mnt/ca-root create --ca-name root --filename ca.$DOMAIN --intermediate "Certificate Authority for ca.$DOMAIN"
# mv /mnt/ca-root/ca.$DOMAIN /mnt/ca/ca.$DOMAIN

vault-umount $1


