#!/bin/sh

# This is a script to mount the encrypted ca.vhd making it available to the pki docker container.
# VAULT=$1
# PKI_PATH="/home/mada/Development/Configuration/pki"
# VHD_FILE="$PKI_PATH/disks/$VAULT.vhd"
# VAULT_PATH="$PKI_PATH/vaults/$VAULT"
# echo $VAULT_PATH
# if [ -f $VHD_FILE ] ; then
#     if [ -f "$VAULT_PATH/.last" ] ; then
#         echo "Vault '$VAULT' is already mounted"
#     else
#         sudo cryptsetup luksOpen "$VHD_FILE" "$VAULT.crypt"
#         sudo mount "/dev/mapper/$VAULT.crypt" "$VAULT_PATH"
#         date +%s > "$VAULT_PATH/.last"
#     fi
# else
#    echo "Cannot find the virtual hard drive (vhd) file for vault '$VAULT' to mount"
# fi

PKILIB_PATH=/var/lib/pki
if [ -d $PKILIB_PATH ] ; then
 cd $PKILIB_PATH
 if [ -d $PKILIB_PATH/.git ] ; then 
   echo "Updating ecrypted virtual drives"
   git pull
 else
   echo "No repository found, Key repository should be cloned to ($PKILIB_PATH)"
 fi
 for p in $PKILIB_PATH/*.evd ; do # loop through the evd files 
   if [ -f $p ] ; then
     f=${p%.evd}
     v=${f##*/}
     if [ -d /mnt/pki/$v ] ; then
       read -n3 -p "Decrypt and mount encrypted virtual drive $p as $v_vd? (type capitalized 'yes' to confirm)" confirm 
       echo
       case $confirm in  
         "YES") echo "Opening $p as $v_vd" \
               && sudo cryptsetup luksOpen "$p" "$v_vd" \
               && echo "Mounting $v_vd as /mnt/pki/$v" \
               && sudo mount "/dev/mapper/$v_vd" "/mnt/pki/$v" ;; 
         *) echo "Will nout mount $v." ;; 
       esac
       echo "Completed with exit code $?"
     else
       echo "No mount point (/mnt/pki/$v) found"
     fi
   fi
  done
else
  echo "No pki library found ($PKILIB_PATH)"
fi
cd
