#!/bin/sh

# This is a script to mount the encrypted ca.vhd making it available to the pki docker container.

if [ -d /home/pki/keys ] ; then
 cd /home/pki/keys
 if [ -d /home/pki/keys/.git ] ; then 
   echo "Updating ecrypted virtual drives"
   git pull
 else
   echo "No key repository found"
 fi
 for p in /home/pki/keys/*.evd ; do # loop through the evd files 
   if [ -f $p ] ; then
     f=${p%.evd}
     v=${f##*/}
     if [ -d /mnt/pki/$v ] ; then
       read -n4 -p "Decrypt and mount encrypted virtual drive $p as $v? (type capitalized 'yes' to confirm) " confirm 
       echo
       case $confirm in  
         "YES") echo "Opening $p as $v" \
               && sudo cryptsetup luksOpen $p $v \
               && echo "Mounting $v as /mnt/pki/$v" \
               && sudo mount "/dev/mapper/$v" "/mnt/pki/$v" ;; 
         *) echo "Will not mount $v." ;; 
       esac
       if [ $? -eq 0 ] ; then
	 echo "Successfully mounted $v."
         date +%s > "/mnt/pki/$v/.last"
       else
	 echo "Failed with exit code $?."
         echo "Attempting Rollback"
         sudo umount "/mnt/pki/$v"
         sudo cryptsetup luksClose $v
       fi
       echo "Completed with exit code $?."
     else
       echo "No mount point (/mnt/pki/$v) found."
     fi
   fi
  done
else
  echo "Key repository not configured."
fi
cd
