#!/bin/sh

# vault-umount: Unmounts from mount point and closes the device placing back into secure encrypted state. This script should be fail safe and attemp to put the vault in the most secure state possible.

MOUNT_POINT=/mnt/vault

# echo "[INFO] Unmount vault"
/bin/mountpoint -q $MOUNT_POINT
if [ $? -eq 0 ] ; then
 /usr/bin/sudo /bin/umount $MOUNT_POINT
fi

# echo "[INFO] Close vault"
/usr/bin/sudo /sbin/cryptsetup status vault >> /dev/null
if [ ! $? -eq 4 ] ; then
 /usr/bin/sudo /sbin/cryptsetup luksClose vault
fi

# echo [INFO] Clean up mount point
/bin/mountpoint -q $MOUNT_POINT
if [ $? -eq 1 ] ; then
 /usr/bin/sudo rm -rf $MOUNT_POINT
fi
