#!/bin/sh

# Creates vhd, encrypts into evhd, mounts, unmounts

VAULT=$1
# echo "Confirm source location"
# sudo mkdir -p /opt/pki
# sudo chown pki:pki -R /opt/pki

echo "Create mount point for vault($VAULT)"
sudo mkdir -p /mnt/$VAULT

if [ ! -f "/opt/pki/$VAULT.vhd" ] ; then
 echo "Creating virtual hard drive for vault($VAULT)"
 dd if=/dev/urandom of=/opt/pki/$VAULT.vhd bs=1M count=20
 
 echo "Encrypting virtual hard drive for vault($VAULT)"
 cryptsetup -y luksFormat /opt/pki/$VAULT.vhd
 
 echo "Opening encrypted virtual hard drive for $VAULT"
 sudo cryptsetup luksOpen /opt/pki/$VAULT.vhd $VAULT.evhd
 
 echo "Formating encrypted virtual hard drive for vault($VAULT)"
 sudo mkfs.ext4 /dev/mapper/$VAULT.evhd
 
 echo "Mount vault($VAULT) into mount point"
 sudo mount /dev/mapper/$VAULT.evhd /mnt/$VAULT
  
 echo "Foring ownership for vault($VAULT)"
 sudo chown -R pki:pki /mnt/$VAULT
 
 echo "Checking success for vault($VAULT)"
 df -h
 echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
 vault-refresh $VAULT
 exit 0
else
 echo "[ERROR] There is an existing virtual hard drive for vault($VAULT)"
 exit 99
fi
