#!/bin/sh

# Creates vhd, encrypts into evhd, mounts, unmounts

VAULT=$1
# echo "Confirm source location"
# sudo mkdir -p /opt/pki
# sudo chown pki:pki -R /opt/pki

echo "Create mount point for vault($VAULT)"
sudo mkdir -p /mnt/$VAULT

if [ ! -f "/opt/pki/$VAULT.vhd" ] ; then
 echo "Creating virtual hard drive for vault($VAULT)"
 /bin/dd if=/dev/urandom of=/opt/pki/$VAULT.evhd bs=1M count=100
 
 echo "Encrypting virtual hard drive for vault($VAULT)"
 /sbin/cryptsetup --type=luks2 --verify-passphrase luksFormat /opt/pki/$VAULT.evhd
 
 echo "Opening encrypted virtual hard drive for $VAULT"
 /usr/bin/sudo /sbin/cryptsetup luksOpen /opt/pki/$VAULT.evhd $VAULT.vhd
 
 echo "Formating encrypted virtual hard drive for vault($VAULT)"
  /usr/bin/sudo /sbin/mkfs.ext4 /dev/mapper/$VAULT.evhd
 
 echo "Mount vault($VAULT) into mount point"
 /usr/bin/sudo /bin/mount /dev/mapper/$VAULT.evhd /mnt/$VAULT
  
 echo "Foring ownership for vault($VAULT)"
  /usr/bin/sudo /bin/sudo chown -R pki:pki /mnt/$VAULT
 
 echo "Checking success for vault($VAULT)"
 /bin/df -h
 echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
 /usr/bin/vault-refresh $VAULT
 exit 0
else
 echo "[ERROR] There is an existing virtual hard drive for vault($VAULT)"
 exit 99
fi
