#!/bin/sh

VAULT=$1
echo "Confirm source location"
mkdir -p /opt/pki-data

echo "Create mount point for vault($VAULT)"
mkdir -p /mnt/$VAULT

if [ ! -f "/opt/pki-data/$VAULT.vhd" ] ; then
 echo "Creating virtual hard drive for vault($VAULT)"
 dd if=/dev/urandom of=/opt/pki-data/$VAULT.vhd bs=1M count=20
 
 echo "Encrypting virtual hard drive for vault($VAULT)"
 cryptsetup -y luksFormat /opt/pki-data/$VAULT.vhd
 
 echo "Opening encrypted virtual hard drive for $VAULT"
 sudo cryptsetup luksOpen /opt/pki-data/$VAULT.vhd $VAULT.evhd
 
 echo "Formating encrypted virtual hard drive for vault($VAULT)"
 sudo mkfs.ext4 /dev/mapper/$VAULT.evhd
 
 echo "Mount vault($VAULT) into mount point"
 sudo mount /dev/mapper/$VAULT.evhd /mnt/$VAULT
  
 echo "Foring ownership for vault($VAULT)"
 sudo chown -R pki:pki /mnt/ca
 
 echo "Checking success for vault($VAULT)"
 df -h
 echo "- - - - -"
 sudo cryptsetup luksStatus $VAULT.evhd
 echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
 
 echo "Unmount vault($VAULT) from mount point"
 sudo umount /mnt/$VAULT
 
 echo "Close encrypted virtual hard drive for vault($VAULT)"
 sudo cryptsetup luksClose $VAULT.evhd
else
 echo "[ERROR] There is an existing virtual hard drive for vault($VAULT)"
fi

