#!/bin/sh

# vault-refresh: This script, called after vault operations, updates the timestamp file refreshing the vaults keep-alive ticker

# Check the mount point force if needed
/bin/mountpoint -q /mnt/vault
if [ $? -eq 0 ] ; then
 date +%s > /mnt/vault/.last
else
 echo "[ERROR] Vault(/opt/pki/vault.evhd) is not mounted(/mnt/vault)" >&2
fi
