#!/bin/sh

# Simple script to unmount the pki vaults


VAULT=$1

unmount_vault () {
  mountpoint "/mnt/pki/$1"
  if [ $? -eq 0 ] ; then
    sudo umount "/mnt/pki/$1"
  else
    echo "Nothing to unmount"
  fi
  echo "Closing device $1"
  if [ -e "/dev/mapper/$1" ] ; then # check device exists
    sudo cryptsetup luksClose $1
  else
    echo "$1 virtual device not found"
  fi
}

if [ "all" == "$VAULT" ] ; then
  for mp in /mnt/pki/* ; do # loop through the moint points
   if [ -d $mp ] ; then
    v=${mp##*/}
    unmount_vault $v
   fi
  done 
else
  unmount_vault $VAULT
fi

# if [ -f "/opt/docker/pki/vaults/$VAULT.vault/.last" ] ; then
#     sudo umount /opt/docker/pki/vaults/$VAULT.vault
#     sudo cryptsetup luksClose /dev/mapper/$VAULT.crypt
# else
#     echo "Vault '$VAULT' is not mounted"
# fi
#  
# for mp in /mnt/pki/* ; do # loop through the moint points 
#    if [ -d $mp ] ; then
#    fi
# done
