#!/bin/sh

# This script runs every 15 minutes to unmount a vault that has not been refreshed in the last 3 minutes.

MINUTES=3
MOUNT_POINT=/mnt/vault

if [ -f "$MOUNT_POINT/.last" ] ; then
 TIMEOUT=$((($MINUTES * 60)))
 LAST_TIMESTAMP=$(cat $MOUNT_POINT/.last)
 CURRENT_TIMESTAMP=$(date +%s)
 DELTA_TIMESTAMP=$((($CURRENT_TIMESTAMP - $LAST_TIMESTAMP)))
 if [ 1 = $((($DELTA_TIMESTAMP < $TIMEOUT))) ] ; then
  REMAIN=$(date -u -d @$((($TIMEOUT - $DELTA_TIMESTAMP))) +"%T")
  echo "Vault will auto-lock in $REMAIN"
  exit 0
 fi
fi

# This is the defualt mechanism to clean-up the vault to a secure point
/usr/bin/vault-umount
