#!/bin/sh

# This script runs every 15 minutes to unmount a vault that has not been refreshed in the last 3 minutes.

unmount()
{
    VAULT=$1
    if [ -f /mnt/$VAULT/.last ] ; then
        MINUTES=3
        TIMEOUT=$((($MINUTES * 60)))
        LAST_TIMESTAMP=$(cat /mnt/$VAULT/.last)
        CURRENT_TIMESTAMP=$(date +%s)
        DELTA_TIMESTAMP=$((($CURRENT_TIMESTAMP - $LAST_TIMESTAMP)))
        if [ 1 = $((($DELTA_TIMESTAMP > $TIMEOUT))) ] ; then
            vault-umount $VAULT
        fi
    fi
}


umount ca-root
umount ca
